"""rename department

Revision ID: 034d077d5b08
Revises: 946d24f833c1
Create Date: 2025-01-14 13:36:26.160135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034d077d5b08'
down_revision = '946d24f833c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###