"""add Department

Revision ID: 946d24f833c1
Revises: 5f97c12a5115
Create Date: 2025-01-14 13:28:36.721529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946d24f833c1'
down_revision = '5f97c12a5115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
